/* Real API + two browser tabs. Run against the isolated studio4_media_smoke project. */
let playwright;try{playwright=require('playwright')}catch{playwright=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright')}
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage']});
try{let context=await browser.newContext({viewport:{width:1440,height:1080}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});
 await page.goto(process.argv[2]);await page.waitForFunction(()=>document.querySelector('#projects').options.length>1);
 const pid=await page.locator('#projects option').nth(1).getAttribute('value');await page.locator('#projects').selectOption(pid);
 await page.getByRole('button',{name:'Analisis sumber',exact:true}).waitFor();await page.locator('[data-step="story"]').click();await page.getByRole('button',{name:'Edit klip ini →',exact:true}).first().click();await page.getByLabel('Kata 0',{exact:true}).waitFor();
 await page.locator('[data-view="preview"]').click();await page.waitForFunction(()=>document.querySelector('#player-video')?.readyState>=2);await page.locator('#player-video').evaluate(v=>{v.currentTime=5.5});await page.waitForFunction(()=>!document.querySelector('#player-video').seeking);assert.ok(await page.locator('#player-video').evaluate(v=>v.getBoundingClientRect().height<=v.parentElement.getBoundingClientRect().height+1));await page.screenshot({path:process.argv[3]+'/editor.png',fullPage:true});
 const draftText='Draf '+Date.now(),draft=page.getByLabel('Kata 0',{exact:true});await draft.fill(draftText);
 const tab=await context.newPage();await tab.goto(process.argv[2]);
 const mutation=await tab.evaluate(async pid=>{const doc=await (await fetch('/api/studio/projects/'+pid)).json(),cid=Object.keys(doc.clips)[0];const r=await fetch('/api/studio/changes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:pid,clip_id:cid,variant_id:'portrait',expected_revision:doc.revision,operation_id:crypto.randomUUID(),operations:[{op:'settings',values:{music_db:-31}}]})});return {status:r.status,data:await r.json()}},pid);assert.equal(mutation.status,200);
 await page.getByRole('button',{name:'Simpan koreksi kata',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('tab lain'));
 assert.equal(await draft.inputValue(),draftText);
 await page.locator('.toolbar').getByRole('button',{name:'Muat revisi terbaru',exact:true}).click();await page.getByLabel('Kata 0',{exact:true}).waitFor();assert.equal(await page.getByLabel('Kata 0',{exact:true}).inputValue(),draftText);
 await page.getByRole('button',{name:'Simpan koreksi kata',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('tersimpan'));
 const words=await page.evaluate(async pid=>(await (await fetch('/api/studio/projects/'+pid+'/words?clip_id='+Object.keys((await (await fetch('/api/studio/projects/'+pid)).json()).clips)[0])).json()).words,pid);assert.equal(words[0].word,draftText);assert.equal(words[0].heard,'Pahami');
 await page.getByText('Tata teks & komposisi',{exact:true}).click();await page.getByLabel('Skala huruf',{exact:true}).fill('1.1');await page.getByRole('button',{name:'Simpan tata teks',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('tersimpan'));
 await page.getByLabel('Rasio',{exact:true}).selectOption('landscape');await page.getByText('Tata teks & komposisi',{exact:true}).click();assert.equal(await page.getByLabel('Skala huruf',{exact:true}).inputValue(),'1');
 await page.getByText('Ilustrasi & bukti analisis',{exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.analysis-card video')].some(v=>v.readyState>=1));assert.ok(await page.locator('.analysis-card video').getAttribute('poster'));
 await page.locator('[data-view="final"]').click();await page.screenshot({path:process.argv[3]+'/landscape.png',fullPage:true});
 await page.getByRole('button',{name:'Berkas & cache',exact:true}).click();await page.getByRole('dialog').waitFor();assert.ok(await page.locator('dialog input[type="checkbox"]:disabled').count()>0);assert.ok(await page.locator('dialog input[type="checkbox"]:not(:disabled)').count()>1);await page.screenshot({path:process.argv[3]+'/storage.png',fullPage:true});await page.getByRole('button',{name:'Tutup',exact:true}).click();
 await page.locator('[data-step="results"]').click();await page.getByRole('link',{name:'Unduh MP4',exact:true}).first().waitFor();assert.equal(await page.getByRole('link',{name:'Unduh MP4',exact:true}).count(),2);
 assert.deepEqual(errors,[]);const report={passed:true,fixture:'real FastAPI/SQLite + synthetic media',checks:['four_step_navigation','preview_playback','two_tab_conflict','draft_preserved','explicit_refresh_keeps_draft','sparse_correction_persisted','original_transcript_immutable','independent_ratios','asset_preview_and_poster','protected_files_disabled','both_final_results'],page_errors:errors};fs.writeFileSync(process.argv[3]+'/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
