"""Real SQLite service/queue tests. Video fixture is generated by FFmpeg."""
from dataclasses import replace
import json
from pathlib import Path
import subprocess
import tempfile
import unittest
from clipper.config import Config
from clipper.studio_service import StudioService
from clipper.project_store import Conflict


class StyleService(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.media_temp=tempfile.TemporaryDirectory();cls.source=Path(cls.media_temp.name)/'source.mp4'
        subprocess.run(['ffmpeg','-nostdin','-v','error','-y','-f','lavfi','-i','color=s=320x180:r=30:d=6','-f','lavfi','-i',
            'sine=frequency=260:duration=6','-c:v','libx264','-threads','1','-c:a','aac','-shortest',str(cls.source)],capture_output=True,check=True)
    @classmethod
    def tearDownClass(cls):cls.media_temp.cleanup()
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory();self.svc=StudioService(self.temp.name,Config(use_nvenc=False),autostart=False)
        self.doc=self.svc.create(self.source)
        self.take='asr-fixture';rows=[{'word':'kata','word_id':i,'start':i*.5,'end':(i+1)*.5} for i in range(12)]
        self.svc.store.save_transcript(self.doc['project_id'],{'words':rows},self.take)
        def initial(d):
            d['transcript_id']=self.take
            self.svc.add_candidates(d,[{'title':'Klip uji','start':0.,'end':6.,'keywords':[]}])
        self.svc.store.mutate(self.doc['project_id'],0,'initial-fixture',{},initial)
        self.doc=self.svc.store.get(self.doc['project_id']);self.cid=next(iter(self.doc['clips']))
    def tearDown(self):self.temp.cleanup()
    def request(self,values,revision=None,variant='portrait'):
        return {'project_id':self.doc['project_id'],'clip_id':self.cid,'variant_id':variant,'expected_revision':self.doc['revision'] if revision is None else revision,
                'operation_id':'change-'+str(revision)+'-'+variant,'operations':[{'op':'settings','values':values}]}
    def test_settings_only_affect_selected_ratio(self):
        self.svc.changes(self.request({'style_preset':'ekspresif','caption_seed':77}))
        current=self.svc.store.get(self.doc['project_id']);p=self.svc.config(current,self.cid,'portrait');l=self.svc.config(current,self.cid,'landscape')
        self.assertEqual((p.style_preset,p.caption_seed),('ekspresif',77));self.assertEqual(l.style_preset,'legacy')
    def test_changes_invalidate_preview_dependency(self):
        old=self.svc.dependency(self.doc,self.cid,'portrait');self.svc.changes(self.request({'style_preset':'rapi'}))
        current=self.svc.store.get(self.doc['project_id']);self.assertNotEqual(old,self.svc.dependency(current,self.cid,'portrait'))
    def test_style_job_queued_with_current_dependency(self):
        job=self.svc.enqueue(self.doc['project_id'],'style_review',self.cid,'landscape',self.doc['revision'])
        self.assertEqual(job['kind'],'style_review');self.assertEqual(job['target']['variant_id'],'landscape')
        self.assertEqual(job['request']['dependency'],self.svc.dependency(self.doc,self.cid,'landscape'))
    def test_job_requires_clip(self):
        with self.assertRaises(ValueError):self.svc.enqueue(self.doc['project_id'],'style_review',None,'portrait',self.doc['revision'])
    def test_stale_revision_cannot_save(self):
        self.svc.changes(self.request({'caption_seed':4}))
        with self.assertRaises(Conflict):self.svc.changes({**self.request({'caption_seed':5}),'operation_id':'stale-change'})
    def test_invalid_settings_leave_project_unchanged(self):
        with self.assertRaises(ValueError):self.svc.changes(self.request({'caption_seed':-9}))
        self.assertEqual(self.svc.store.get(self.doc['project_id']),self.doc)
    def test_report_becomes_stale_after_settings_change(self):
        dependency=self.svc.dependency(self.doc,self.cid,'portrait')
        def initial(d):d['clips'][self.cid]['variants']['portrait'].update(style_report={'phrases':[],'issue_count':0},style_dependency=dependency)
        saved=self.svc.store.mutate(self.doc['project_id'],self.doc['revision'],'seed-report',{},initial)
        self.assertFalse(self.svc.public(self.doc['project_id'])['clips'][self.cid]['variants']['portrait']['style_report']['stale'])
        self.svc.changes(self.request({'caption_seed':99},saved['revision']))
        self.assertTrue(self.svc.public(self.doc['project_id'])['clips'][self.cid]['variants']['portrait']['style_report']['stale'])
    def test_model_generation_changes_dependency(self):
        cfg=self.svc.config(self.doc,self.cid,'portrait');old=self.svc.dependency(self.doc,self.cid,'portrait')
        root=Path(cfg.visual_runtime_root);generation=root/'generations/motion-fixture';generation.mkdir(parents=True)
        (generation/'receipt.json').write_text(json.dumps({'installed':True,'test':{'passed':True,'level':'build'}}))
        active=root/'components/motion-canvas/active.json';active.parent.mkdir(parents=True);active.write_text(json.dumps({'generation':'motion-fixture'}))
        self.assertNotEqual(old,self.svc.dependency(self.doc,self.cid,'portrait'))


if __name__=='__main__':unittest.main()
