# Profil lokal Intel i5 gen 12 / RAM 40 GB / RTX 3050 4 GB.
# Ubah file ini untuk tuning. Tidak memakai API berbayar.
CLIPPER_MODEL=qwen3:8b
OLLAMA_URL=http://127.0.0.1:11434
OLLAMA_NUM_GPU=16
OLLAMA_NUM_CTX=4096
OLLAMA_TIMEOUT=1200
WHISPER_MODEL=medium
WHISPER_DEVICE=auto
WHISPER_COMPUTE=int8_float16
WHISPER_ISOLATE=1
TRANSCRIPT_LANGUAGE=id
CAPTION_STYLE=editorial
ACCENT_HEX="#FFC52F"
FONT_NAME=DejaVu Sans
CAPTION_POSITION=auto
CAPTION_SCALE=1.0
EDITORIAL_WORDS=6
EDITORIAL_PHRASE_S=2.6
CAPTION_GAP_S=0.55
USE_NVENC=1
AUDIO_NORMALIZE=1
TRIM_SILENCE=0
PUNCH_ZOOM=0
BROLL=0
NUM_CLIPS=4
